paulscherrerinstitute/ecmccfg

scripts/applySlaveConfig.cmd

apply only configuration to slave

---

db/ecmcPlc.db
examples/ESS_crate_slit/ess_crate.script
protocol/ecmcPlc.proto
scripts/loadPLCFile.cmd

@anderssandstrom
I added a simple db file to enable/disable PLCs.
Is there a way to determine the state of a PLC similar to `GetAxisPLCEnable(n)`?

Plc enable pv

---

db/Beckhoff_7XXX/ecmcEL7211-0010.substitutions
hardware/Motors/ecmcEL7211-0010-Motor-Beckhoff-AM8113-0F21-0000.cmd

Added EL7211-0010 missing subs
Added Beckhoff AM8113 motor

EL7211-0010 and AM8113 motor

---

examples/test/autoEnableDisable/ReadMe.md
examples/test/autoEnableDisable/cfg/linear_1_auto_on_off.ax
motion/ecmc_axis.cmd

* Add "CFG_MACROS" param to configureAxis.cmd
* Add example on how to use "CFG_MACROS"
* Add default values for all LATCH related variables in ecmc_axis.cmd to avoid MACRO expansion failure if more than one axis is used.

Minor updates

---

startup.cmd

disable master by setting the MASTER_OD to a negative number.
i.e.
```
require ecmccfg dev "MASTER_ID=-1, ECMC_VER=dev"
```

new feature: disable master

---

db/Beckhoff_7XXX/ecmcEP7041.substitutions
db/Beckhoff_7XXX/ecmcEP7211-0034_CSP.substitutions
examples/test/csp/ep7211/cfg/ep7211_CSP.pax
examples/test/csp/ep7211/ep7211-0034_CSP.iocsh
hardware/Beckhoff_slaves/ecmcEP7211-0034_CSP.cmd

the reset to "0"t startup makes an absolute encoder kinda useless.

EP7211-0043, CSP tested

---

scripts/loadPLCFile.cmd

Calculate PLC sample rate if not explicitly declared, I know I'm lazy :)

auto sample rate for PLC

---

db/Baumer/ecmcEAM580-chX.template
db/Baumer/ecmcEAM580.substitutions
db/Baumer/ecmcEAx580-chX.template
db/Baumer/ecmcEAx580.substitutions
hardware/Baumer/ecmcEAM580.cmd
hardware/Baumer/ecmcEAx580.cmd

Baumer: New naming concept

---

db/core/ecmcAxis.db
db/core/ecmcDS-idx.template
db/core/ecmcPlc.db

V7.0.0 motion

---

db/core/ecmcEc.db
db/core/ecmcEcSlave.template
db/core/ecmcGeneral.db

Update parts of PV names to capital letters

V7.0.0 capital

---

db/core/ecmcEcSlave.template

fixed issue 104

---

GNUmakefile
db/Beckhoff_3XXX/ecmcEL3204.substitutions
scripts/addSlave.cmd
scripts/applySubstitutions.cmd
scripts/applyTemplate.cmd

#99 
default PVs for PDOs can now be turned off.

disable default records

---

hugo/content/manual/axis/axisYaml.md

let's try this pipeline doc thingy again :)

more doc, WIP

---

GNUmakefile
db/core/ecmcAxis.db
db/core/ecmcMotorRecordhome.template
motion/ecmc_axis-records.cmd
scripts/jinja2/templates/epicsAxis.jinja2

@anderssandstrom @imohacsi
please look at this https://github.com/paulscherrerinstitute/ecmccfg/commit/40f00d5f59fdae63abcfc4ac96248c6e86146f99
It's potentially breaking things at your end.

`MtnCmdData` based on selected mode of motion

---

hardware/Motors/ecmcEL7041-Motor-OrientalMotor-ARM24SAK-H50.cmd
hardware/Motors/ecmcEL7041-Motor-OrientalMotor-ARM46AK-H50.cmd
hardware/Motors/ecmcEL7041-Motor-Phytron-VSS-57.200.1.2.cmd

Adding three motor combinations:
EL7041-Motor-OrientalMotor-ARM24SAK-H50
EL7041-Motor-OrientalMotor-ARM24SAK-H50
EL7041-Motor-Phytron-VSS-57.200.1.2

Adding two extra Oriential and one Phytron motors

---

hugo/content/manual/axis/axisYaml.md
qt/ecmcAxis_v10.ui
qt/ecmcEK1100_S.ui
qt/ecmcEL5042_S.ui
qt/ecmcEL5101_S.ui
qt/ecmcEL70x1_S.ui
qt/ecmcEL9227_S.ui
qt/ecmcEL9410_S.ui
qt/ecmcEL9576_S.ui
qt/ecmcE_slave_frame_S.ui
qt/ecmcEx10x4_S.ui
qt/ecmcEx20x4_S.ui
qt/ecmcEx3xx4_S.ui
qt/ecmcEx5001_S.ui
qt/ecmcEx70x7_S.ui
qt/ecmcPowerSupply_S.ui

New panels are just 100x400 pixels, so two lines should fit a FHD notebook screen.
Also added axis panel with online PID tuning interface.

Adding smaller panels for 1080p screens

---

hardware/Motors/ecmcEL7037-Motor-Phytron-VSS-80.200.5.cmd
hardware/Motors/ecmcEL7041-0052-Motor-Phytron-VSS-80.200.5.cmd
hardware/Motors/ecmcEL7041-Motor-Phytron-VSS-80.200.5.cmd
hardware/Motors/ecmcEL7047-Motor-Phytron-VSS-80.200.5.cmd

[Motor manual](https://github.com/paulscherrerinstitute/ecmccfg/files/12599269/ds-vacuum-en.pdf)

Add Phytron VSS 80.200.5

---

db/Beckhoff_7XXX/ecmcELM7222-0010.substitutions
examples/test/elm7222/cfg/AM8112_ch1.yaml
examples/test/elm7222/cfg/AM8112_ch2.yaml
examples/test/elm7222/startup_ch1.iocsh
examples/test/elm7222/startup_ch2.iocsh
examples/test/elm7321/startup.iocsh
hardware/Beckhoff_7XXX/ELM/ecmcELM7222-0010.cmd
hardware/Motors/ecmcELM7222-0010-Motor-ch1-Beckhoff-AM8112-xFx1.cmd
hardware/Motors/ecmcELM7222-0010-Motor-ch2-Beckhoff-AM8112-xFx1.cmd

Added support for ELM7222-0010 dual channel servo drive.

ELM7222-0010

---

hardware/Encoders/ecmcEL5042-Encoder-Postital-UCD-S101B-1416-XXXX-XXX.cmd
hardware/Encoders/ecmcEL5042-Encoder-ch1-Posital-UCD-S101B-1416-XXXX-XXX.cmd
hardware/Encoders/ecmcEL5042-Encoder-ch2-Posital-UCD-S101B-1416-XXXX-XXX.cmd

Posital UCD-S101B-1416 encoder implemented for EL5042.
I don't have the dedicated SSI-terminal, so I can't test it on anything other than the EL5042

Posital UCD-S101B1416, SSI encoder

---

scripts/jinja2/ecmcYamlHandler.py
scripts/jinja2/pytest/test_ecmcAxes.py

missing path added for pytest to properly import modules

fixed errors from pytest

---

hardware/Beckhoff_3XXX/EL/ecmcEL3174-0002.cmd

Just add a link pointing to EL3174

Add EL3174-0002 support
